test:
  stage: test
  script:
    - docker build --tag phpwithintlandcomposer:1.0 .
    - docker run --rm --volume $PWD:/app phpwithintlandcomposer:1.0 test
    - docker run --rm --volume $PWD:/app phpwithintlandcomposer:1.0 cs
